[package]
name = "lab0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.20.0"
socket2 = "0.4.2"
rand = "0.8.4"
